resilience4j.retry:
    instances:
        passenger:
            registerHealthIndicator: true
            maxAttempts: 10
            waitDuration: 5s
            
            
            
resilience4j.circuitbreaker:
  instances:
    passenger:
      registerHealthIndicator: true
      slidingWindowSize: 10
      slidingWindowType: TIME_BASED
      permittedNumberOfCallsInHalfOpenState: 3
      failureRateThreshold: 50
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 5s
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 2000
      automaticTransitionFromOpenToHalfOpenEnabled: true
            
resilience4j.ratelimiter:
  instances:
    passenger:
      limitRefreshPeriod: 24s
      limitForPeriod: 5
      timeoutDuration: 20s
      registerHealthIndicator: true        
            
management:
  endpoint:
    health:
      show-details: always         #To show all details in /health endpoint.

management.health.circuitbreakers.enabled: true


#eureka client config
spring:
 application:
  name: LopHoc-SERVICE
 config:
  import:optional:configserver:
 cloud:
  config:
   uri: http://localhost:8888


